name: badge

on:
  workflow_run:
    workflows: [analysis]
    types:
      - completed

jobs:
  #  run_on_workflow_a_success:
  #    if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Run on workflow A success
  #        run: echo "Workflow A completes successfully"

  deploy:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Download artifact Linux GCC
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: analysis.yml
          name: phpinsights
          path: phpinsights


      #      - name: Download test results
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        run: gh run download "$GITHUB_RUN_ID" --dir "$RUNNER_TEMP/phpinsights"
      #
      #      - name: get
      #        run: |
      #          gh run download --repo "${{ github.repository}}" --name phpinsights --dir . "${{ github.run_id }}"
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #
      #      - name: Installing dependencies
      #        uses: php-actions/composer@v6
      #        with:
      #          php_version: 8.2
      #          php_extensions: "zip"
      #
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: php
        run: "php badges.php"

      - name: upload
        # Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.svg *.txt *.json'
          commit_message: Badges
