name: Badges

on:
  workflow_run:
    workflows: ["Analysis", "Testing"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: php
        run: "php badges.php"
