name: Badges

on:
  workflow_run:
    workflows: ["Analysis", "Testing"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying the project..."
